## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [54]:
import torch
import torch.nn as nn
from collections import OrderedDict


In [55]:
data_in = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]]).float()
data_target = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]]).reshape(-1, 2).float()
print(data_in)
print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [56]:
def test_model(model, criterion, optimizer, accuracy_function):
    EPOCHS = 10000
    for i in range(EPOCHS):
        output = model(data_in)
        loss = criterion(output, data_target)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if (i + 1) % 1000 == 0:
            print(f'Epoch [{i+1}/{EPOCHS}], Loss: {loss.item():.4f}')
    print(f"Accuracy {accuracy_function(model)}")

In [57]:
# your code here
model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(data_in.shape[1], 1)),
    ('hidden_activation', nn.Sigmoid()),
    ('output', nn.Linear(1, data_target.shape[1]))
]))
criterion1 = torch.nn.BCEWithLogitsLoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)
def accuracy_function1(model):
    with torch.no_grad():
        output = torch.nn.Sigmoid()(model(data_in))
        predicted = (output >= 0.5)
        accuracy = (predicted == data_target).float().mean()
        return accuracy

test_model(model1, criterion1, optimizer1, accuracy_function1)

Epoch [1000/10000], Loss: 0.5832
Epoch [2000/10000], Loss: 0.4974
Epoch [3000/10000], Loss: 0.4232
Epoch [4000/10000], Loss: 0.3668
Epoch [5000/10000], Loss: 0.3275
Epoch [6000/10000], Loss: 0.3031
Epoch [7000/10000], Loss: 0.2880
Epoch [8000/10000], Loss: 0.2782
Epoch [9000/10000], Loss: 0.2715
Epoch [10000/10000], Loss: 0.2666
Accuracy 0.875


In [58]:
# your code here
model2 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(data_in.shape[1], 2)),
    ('hidden_activation', nn.Sigmoid()),
    ('output', nn.Linear(2, data_target.shape[1]))
]))
criterion2 = torch.nn.BCEWithLogitsLoss()
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1)
def accuracy_function2(model):
    with torch.no_grad():
        output = torch.nn.Sigmoid()(model(data_in))
        predicted = (output >= 0.5)
        accuracy = (predicted == data_target).float().mean()
        return accuracy

test_model(model2, criterion2, optimizer2, accuracy_function2)

Epoch [1000/10000], Loss: 0.5384
Epoch [2000/10000], Loss: 0.4477
Epoch [3000/10000], Loss: 0.3776
Epoch [4000/10000], Loss: 0.3279
Epoch [5000/10000], Loss: 0.2751
Epoch [6000/10000], Loss: 0.1603
Epoch [7000/10000], Loss: 0.0872
Epoch [8000/10000], Loss: 0.0566
Epoch [9000/10000], Loss: 0.0414
Epoch [10000/10000], Loss: 0.0325
Accuracy 1.0


In [59]:
# your code here
model3 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(data_in.shape[1], 2)),
    ('hidden_activation', nn.ReLU()),
    ('output', nn.Linear(2, data_target.shape[1]))
]))
criterion3 = torch.nn.BCEWithLogitsLoss()
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.1)
def accuracy_function3(model):
    with torch.no_grad():
        output = torch.nn.Sigmoid()(model(data_in))
        predicted = (output >= 0.5)
        accuracy = (predicted == data_target).float().mean()
        return accuracy

test_model(model3, criterion3, optimizer3, accuracy_function3)

Epoch [1000/10000], Loss: 0.1878
Epoch [2000/10000], Loss: 0.0378
Epoch [3000/10000], Loss: 0.0177
Epoch [4000/10000], Loss: 0.0113
Epoch [5000/10000], Loss: 0.0082
Epoch [6000/10000], Loss: 0.0064
Epoch [7000/10000], Loss: 0.0052
Epoch [8000/10000], Loss: 0.0044
Epoch [9000/10000], Loss: 0.0038
Epoch [10000/10000], Loss: 0.0034
Accuracy 1.0


In [63]:
print(model2[0].weight)
print(model2[0].bias)
print(model2[2].weight)
print(model2[2].bias)

Parameter containing:
tensor([[-4.8102, -4.8085],
        [-5.5543, -5.5529]], requires_grad=True)
Parameter containing:
tensor([1.8795, 8.2186], requires_grad=True)
Parameter containing:
tensor([[ 0.0375, -9.5520],
        [-7.8532,  6.9181]], requires_grad=True)
Parameter containing:
tensor([ 4.0679, -3.0676], requires_grad=True)
